version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root 
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/psql/data/pgdata
    volumes:
      - pgdata:/var/lib/psql/pgdata
  adminer:
    image: adminer
    depends_on: 
      - "db"
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=pgdata
volumes:
  pgdata: